services:
  - type: web
    name: inventory-system
    env: php
    buildCommand: "./render-build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d5lo514oud1c738sfbk0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: inventory_team_8bk0
      - key: DB_USERNAME
        value: inventory_team
      - key: DB_PASSWORD
        value: yVCTTuhQHMww7LKnoq3MwmVufKJBdrcy